### ISSUE TITLE
NameError: global name 'requests' is not defined when running MXNET_course/mxnet-week2/data.py

### ISSUE THREAD

**Issue by BryanBo-Cao** [BitTiger-MP/DS502-AI-Engineer#18]
Attempt to run ```MXNET_course/mxnet-week2/data.py``` (https://github.com/ChuckTan123/MXNET_course/tree/master/mxnet-week2), but got this error
```
➜  mxnet-week2 git:(master) ✗ python data.py
Traceback (most recent call last):
  File "data.py", line 21, in <module>
    train, val = get_mnist(100)
  File "data.py", line 13, in get_mnist
    mnist = mx.test_utils.get_mnist()
  File "/Users/GundamOO/Library/Python/2.7/lib/python/site-packages/mxnet/test_utils.py", line 996, in get_mnist
    path+'train-labels-idx1-ubyte.gz', path+'train-images-idx3-ubyte.gz')
  File "/Users/GundamOO/Library/Python/2.7/lib/python/site-packages/mxnet/test_utils.py", line 983, in read_data
    with gzip.open(mx.test_utils.download(label_url)) as flbl:
  File "/Users/GundamOO/Library/Python/2.7/lib/python/site-packages/mxnet/test_utils.py", line 965, in download
    r = requests.get(url, stream=True)
NameError: global name 'requests' is not defined
```
<img width="1406" alt="screen shot 2017-07-11 at 11 15 16 pm" src="https://user-images.githubusercontent.com/14010288/28104360-838080e2-668f-11e7-8a5f-f12962dfb78c.png">

**Comment by BryanBo-Cao** [comment]
后来在```PyCharm -> Preferences -> Project Interpreter``` 安装 ```requests``` 包之后就好了
<img width="925" alt="screen shot 2017-07-11 at 11 21 02 pm" src="https://user-images.githubusercontent.com/14010288/28104436-d4df3910-668f-11e7-8c25-49cbc375e587.png">
```
➜  mxnet-week2 git:(master) ✗ python data.py
<mxnet.io.NDArrayIter object at 0x1080ec8d0>
[<NDArray 100x1x28x28 @cpu(0)>]
<mxnet.io.NDArrayIter object at 0x10e214650>
➜  mxnet-week2 git:(master) ✗ 

```
